[package]
name = "console_ui_engine"
version = "0.1.0"
authors = ["Harry Null <harryyunull@gmail.com>"]
edition = "2018"

[dependencies]
crossterm = "0.13.2"
rand = "0.7.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }